name: Build (Windows, 2)

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Get latest CMake
      uses: lukka/get-cmake@latest
      
    - name: Build with CMake
      uses: lukka/run-cmake@main
      
    - name: Check output
      run: |
        ls
#        os: [macos-latest, windows-latest, ubuntu-latest]

