name: Build (Windows, 2)

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Get latest CMake
      uses: lukka/get-cmake@latest
      
    - name: Build with CMake
      uses: lukka/run-cmake@main
      with:
        buildDirectory: '${{ github.workspace }}'
      
    - name: Check output
      run: |
        ls

    - name: Store bundles
      uses: actions/upload-artifact@v2
      with:
        name: mocca-windows
        path: build/mocca.exe

#        retention-days: 5
#        path: build/bundles
#        cmakeGenerator: 'VS16Win64'
#        os: [macos-latest, windows-latest, ubuntu-latest]
#      cmakeAppendedArgs: ' -GNinja'

