name: Build (Windows, 2)

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Get latest CMake
      uses: lukka/get-cmake@latest
      
    - name: Build with CMake
      uses: lukka/run-cmake@main
      with:
        buildDirectory: '${{ github.workspace }}'
      
    - name: Check output
      run: |
        ls

    - name: Store bundles
      uses: actions/upload-artifact@v2
      with:
        name: mocca-windows
        path: mocca.exe
      
#    - name: Test
#      run: |
#        mocca.exe

