name: Build (Debian)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Get latest CMake
      uses: lukka/get-cmake@latest
      
    - name: Install dependencies
      run: |
        sudo apt install build-essential devscripts debhelper docbook-to-man cmake
      
    - name: Build package
      run: |
        debuild -b -uc -us
      
    - name: Install package
      run: |
        sudo apt install ../mocca_*.deb
      
    - name: Test
      run: |
        mocca -motif:XML '${{ github.workspace }}/tutorial/motifs2019.xml' -C:CPREdictor -train:FASTA '${{ github.workspace }}/tutorial/KahnPcG.fa' + full -train:FASTA '${{ github.workspace }}/tutorial/tCDS.fa' - full

    - name: Store bundles
      uses: actions/upload-artifact@v2
      with:
        name: mocca-windows
        path: '../mocca_*.deb'
        retention-days: 2

